# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6aab4ca0888b83e25851ab349fe2e3d0ca2314a77c4bd9c77b5ab775e30592b388dcd77994655359a3f299066efcb66bac515223562344e1d9926e76fd6609dc

test:
  secret_key_base: ef9d813c92994cb4bffb9553eee8b692029a2d3d7aba6ecd3e3b5d24a73cb23b2d3dcaada493cf5109184b1ba148da611483d1f73c9e036c2c782a14b645bb8d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
